FROM node:18.14.2-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . .

ENV PORT=3005
ENV NODE_ENV production
ENV MATTERMOST_WEBHOOK_URL https://MATTERMOST_DOMAIN_NAME/hooks/TOKEN
ENV JAEGAR_API_URL http://JAEGER_DOMAIN_NAME/api/traces?service=task-service&tags=%7B%22error%22%3A%22true%22%7D
ENV ENV JAEGAR_DOMAIN_URL http://JAEGER_DOMAIN_NAME
ENV MATTERMOST_CHANNEL_ID CHANNEL_ID

EXPOSE 3005

CMD ["node", "index.js"]